# Generated by Django 3.2.3 on 2022-06-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
