# Generated by Django 3.2.3 on 2022-08-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_gameorder_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
