# Generated by Django 3.2.3 on 2022-08-05 23:33

from django.db import migrations, models
import django.utils.timezone
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('cover_image', models.ImageField(upload_to=store.models.cover_upload_blog_path)),
                ('content_one', models.TextField()),
                ('content_two', models.TextField(blank=True)),
                ('content_three', models.TextField(blank=True)),
                ('image_one', models.ImageField(blank=True, upload_to=store.models.upload_blog_path)),
                ('image_two', models.ImageField(blank=True, upload_to=store.models.upload_blog_path)),
                ('image_three', models.ImageField(blank=True, upload_to=store.models.upload_blog_path)),
            ],
        ),
    ]
